# Generated by Django 6.0.4 on 2026-04-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('pk', models.CompositePrimaryKey('event', 'artist', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'event_artist',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='accountrole',
            table='account_role',
        ),
    ]
